# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abdf15fde0fc839f0264efe4edbb8ddb65728bac21d463f770dc957237481192b0a4c409cbc0def9497f834494c9a87ce1283c7e93caf5c77a430b494488c624

test:
  secret_key_base: d464a03607f3fcebc95c3c5d8119139790fd42e76c45e9e034faa0e179ab1f2a2077ebe8dd40ff15570731cac0cdeb2db8b5d5d6cc49ce2d72f7a8266672b3fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
